swiftmailer:
    transport:        smtp
    username:         luctio@luctiobackend.online
    password:         Rom41k007
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false